name: dust_app
description: Example application using the Dust framework.
version: 0.0.1
publish_to: "none" # Prevent accidental publishing

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  riverpod: ^3.0.0
  dust_component:
    path: packages/component
  dust_renderer:
    path: packages/renderer
  dust_dom:
    path: packages/dom
  js: ^0.7.0 # For main application if it uses js_interop directly
  dust_router:
    path: packages/router

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  dust_atomic_styles:
    path: packages/atomic_styles
